- hosts: local
  user: vagrant
  roles:
    - setup
    - selinux
    - useradd
    - samba
  
  vars_files:
    - group_vars/management_users.yml
    - group_vars/user_groups.yml
    - group_vars/users.yml